

uzb_lang = "🇺🇿 UZB"
eng_lang = "🇬🇧 ENG"



lang = {
    uzb_lang:{
        "back_to_one":"back_call",
        "back_main":"call_back_main",
        "Narxi":"Narxi",
        "Kartoshka fri":"Kartoshka fri",
        "Kartoshka fri katta":"Kartoshka fri katta",
        "Kartoshka fri kichkina":"Kartoshka fri kichkina",
        "Jaydari kartoshka":"Jaydari kartoshka",
        "Non":"Non",
        "Xalapenyo":"Xalapenyo",
        "kartoshka fri":"kartoshka fri",
        "kartoshka fri katta":"kartoshka fri katta",
        "kartoshka fri kichkina":"kartoshka fri kichkina",
        "jaydari kartoshka":"jaydari kartoshka",
        "non":"non",
        "xalapenyo":"xalapenyo",
        "Haggi_tasnifi":"Tavsif: Baget noni, mayonez, mol go'shti, salat bargi, bodring, pomidor, pishloq, qizil sous,"
                        """ "Brunswick" shirin piyoz halqalari\n Miqdorini tanlang yoki kiriting """,
        "Klab_tasnifi":"Tavsif: Toster non, maxsus sous, bodring, pomidor,"
        " tovuq filesi, salat bargi, pishloq, kartoshka friMiqdorini tanlang yoki kiriting",
        "Minus":"➖",
        "minus":"minus",
        "Plus":"➕",
        "plus":"plus",
        "Son":"1",
        "son":"son",
        "Savatga qo'shish": "🛒 Savatga qo'shish",
        "savatga qo'shish": "savatga qo'shish",
        "Hot-dog":"Hot-dog",
        "Pishloqli Hot-dog":"Pishloqli Hot-dog",
        "Shohona Hot-dog":"Shohona Hot-dog",
        "hot-dog":"hot-dog",
        "pishloqli Hot-dog":"pishloqli Hot-dog",
        "shohona Hot-dog":"shohona Hot-dog",
        "Gamburger":"Gamburger",
        "Chizburger":"Chizburger",
        "Big burger":"Big burger",
        "Big Chizburger":"Big Chizburger",
        "Big doner":"Big doner",
        "Shaurma":"Shaurma",
        "gamburger":"gamburger",
        "chizburger":"chizburger",
        "big burger":"big burger",
        "big Chizburger":"big Chizburger",
        "big doner":"big doner",
        "shaurma":"shaurma",
        "Assorti pitsa":"Assorti pitsa",
        "Pepperoni pitsa":"Pepperoni pitsa",
        "Go'shtli pitsa":"Go'shtli pitsa",
        "Qazi pitsa":"Qazi pitsa",
        "Tovuqli pitsa":"Tovuqli pitsa",
        "assorti pitsa":"assorti pitsa",
        "pepperoni pitsa":"pepperoni pitsa",
        "go'shtli pitsa":"go'shtli pitsa",
        "qazi pitsa":"qazi pitsa",
        "tovuqli pitsa":"tovuqli pitsa",
        "Oqtepa Seti":"Oqtepa Seti",
        "Juftlik Seti":"Juftlik Seti",
        "Baraka Seti":"Baraka Seti",
        "oqtepa Seti":"oqtepa Seti",
        "juftlik Seti":"juftlik Seti",
        "baraka Seti":"baraka Seti",
        "Orginal lavash":"Orginal lavash",
        "Orginal kichik lavash":"Orginal kichik lavash",
        "Pishloqli lavash":"Pishloqli lavash",
        "Pishloqli kichik lavash":"Pishloqli kichik lavash",
        "Tandir lavash":"Tandir lavash",
        "Pishloqli tandir lavash":"Pishloqli tandir lavash",
        "pishloqli tandir lavash":"pishloqli tandir lavash",
        "orginal lavash":"orginal lavash",
        "orginal kichik lavash":"orginal kichik lavash",
        "pishloqli lavash":"pishloqli lavash",
        "pishloqli kichik lavash":"pishloqli kichik lavash",
        "tandir lavash":"tandir lavash",
        "Ketchup":"Ketchup",
        "Chili sous":"Chili sous",
        "Pishloqli sous":"Pishloqli sous",
        "Oq sous":"Oq sous",
        "oq sous":"oq sous",
        "pishloqli sous":"pishloqli sous",
        "chili sous":"chili sous",
        "ketchup":"ketchup",
        "Qaynoq ichimliklar":"Qaynoq ichimliklar",
        "Yahna ichimliklar":"Yahna ichimliklar",
        "yahna ichimliklar":"yahna ichimliklar",
        "qaynoq ichimliklar":"qaynoq ichimliklar",
        "Mujskoy kapriz":"Mujskoy kapriz",
        "Sezar":"Sezar",
        "sezar":"sezar",
        "mujskoy kapriz":"mujskoy kapriz",
        "Jo'ja box":"Jo'ja box",
        "Stips 5 dona":"Stips 5 dona",
        "Stips 3 dona":"Stips 3 dona",
        "Bayts":"Bayts",
        "jo'ja box":"jo'ja box",
        "stips 5 dona":"stips 5 dona",
        "stips 3 dona":"stips 3 dona",
        "bayts":"bayts",
        "Qarsildoq Jo'jalar":"🍗 Qarsildoq Jo'jalar",
        "Salatlar":"🥗 Salatlar",
        "Ichimliklar":"🥤Ichimliklar",
        "Souslar":"🍅 Souslar",
        "Lavashlar":"🌯 Lavashlar",
        "Setlar":"🌯🥤🍟 Setlar",
        "Pistalar":"🍕 Pistalar",
        "Burger va donerlar":"🍔 Burger va donerlar",
        "Hot doglar":"🌭 Hot doglar",
        "Haggi":"🥙 Haggi",
        "Klab sendvich":"🥪 Klab sendvich",
        "Sneklar":"🍟 Sneklar",
        "Asosiy menu":"⬅️ Asosiy menu",
        "username":"",
        "qarsildoq jo'jalar":"callqarsildoq jo'jalar",
        "salatlar":"callsalatlar",
        "ichimliklar":"callichimliklar",
        "souslar":"callsouslar",
        "lavashlar":"calllavashlar",
        "setlar":"callsetlar",
        "pistalar":"callpistalar",
        "burger va donerlar":"callburger va donerlar",
        "hot doglar":"callhot doglar",
        "haggi":"callhaggi",
        "klab sendvich":"callklab sendvich",
        "sneklar":"callsneklar",
        "asosiy menu":"callasosiy menu",
        "name": "Ismingizni kiriting",
        "phone_number":"telefon",
        "phone_change": "📞 Mening nomerim",
        "phone_ask":"*Telefon nomeringizni jonating*",
        "aniq_manzil":"Manzil bo'yicha qo'shimcha ma'lumotingizni kiriting\n"
                      "*Misol uchun:* Podyezd №, qavat №, eshik kodi №, kv №...",
        "Ask_contact": "Telefon raqamni yuborish tugmasini bosing! ",
        "send_contact": "📱 Telefon raqamni yuborish",
        "yes":" ✅ HA",
        "no":" ❎ Yo'q",
        "ask_loc_true":"Buyurtma qilmoqchi bo'lgan manzilingiz:"
                       "*{}*\n"
                       "Ushbu manzilni Tasdiqlaysizmi ?",
        "ask_location": "*Eltib berish* uchun *geo-joylashuvni* jonating! ",
        "location": "📍Geo joylashuvni yuborish ",
        "order": "Buyurtma berish 🛒",
        "about_us": "ℹ️ Biz haqimizda",
        "my_orders": "🛍 Buyurtmalarim",
        "branches": "🏘 Filiallar",
        "rewiev": "✍️ Fikr bildirish",
        "settings": "⚙️Sozlamalar",
        "welcome_text":" Assalomualaykum {} Buyurtma berishni boshlash uchun 🛒" 
                       "Buyurtma berish tugmasini bosing " 
                       "\n\n" 
                       "Shuningdek, aksiyalarni korishingiz va bizning filiallar bilan tanishishingiz mumkin",
        "back": "⬅️ Asosiy menu",
        "🚴‍♂️ Eltib berish": "🚴‍♂️  Eltib berish",
        "🚶 Borib olish": "🚶 Borib olish",
        "borib olish":"*Borib olish* uchun *geo-joylashuvni* jo'nating, \n"
        "sizga yaqin bo'lgan filialni aniqlaymiz",
        "buyurtma turi": "Buyurtma turini tanlang !",
        "ask": "Buyurtmani birga joylashtiramizmi? 🤗",
        "about_us_info": "Biz O‘zbekiston bozorida 12 yildan beri faoliyat yuritamiz va bugungi kunda butun mamlakat bo‘ylab 50 dan ortiq filiallarimiz mavjud. Mazali va to‘yimli taomlar, qulay narxlar, tez yetkazib berish xizmatidan mamnun mijozlar yana va yana bizni tanlamoqda \n"
                          "Qaynoqqina va mazali lavashlarimiz, shaurmayu donerlarimiz, gamburger va pitsalarimizdan albatta tatib ko'rishingizni tavsiya qilamiz va buyurtmangizga tovuq go'shtidan yangiliklarimizni qo'shishni unutmang!"
                          f"\n"
                          f"\n"
                          f"\n"
                          f"\n"
                          f"Yetkazib berish xizmati:  +998781500030",
        "my_last_order": """
        Buyurtma raqami => \n
    Xolati => \n
    Manzil => \n
    Maxsulot nomi => \n
    To'lanadigan summa => \n
    To'langan => """,
    "goback": " ❌ Yopish",
        "branch_names": "Filiallar",
        "about_branches": "Bizning filiallarimiz: 63 (1-10)",
        "about_branches_page_two":"Bizning filiallarimiz: 63 (11-20)",
         "main_menu": " ⬅️ Asosiy menu",
         "main_menu1": " ⬅️ Asosiy menu",
        "back_button1": " ⬅️ Ortga",
        "closest_branch": "Eng yaqin filial 🏠",
        "closest_branch1": "Eng yaqin filial 🏠",
        "next_button": "Keyingi ro'yxat ⏭",
        "next_button1": "Keyingi ro'yxat ⏭",
        "next1": "Keyingisi",
        "cb_next_button1": "Keyingisi",
        "Algoritm": "Algoritm",
        "Andijon-1": "Andijon-1",
        "Bektemir": "Bektemir",
        "Beruniy": "Beruniy",
        "Bodomzor": "Bodomzor",
        "Chigatoy": "Chigatoy",
        "Chilonzor 19": "Chilonzor 19",
        "Chilonzor metro": "Chilonzor metro",
        "Chinoz": "Chinoz",
        "Chirchiq": "Chirchiq",
        "🏠 Algoritm": "Algoritm",
        "🏠 Andijon-1": "Andijon-1",
        "🏠 Bektemir": "Bektemir",
        "🏠 Beruniy": "Beruniy",
        "🏠 Bodomzor": "Bodomzor",
        "🏠 Chigatoy": "Chigatoy",
        "🏠 Chilonzor 19": "Chilonzor 19",
        "🏠 Chilonzor metro": "Chilonzor metro",
        "🏠 Chinoz": "Chinoz",
        "🏠 Chirchiq": "Chirchiq",
        "Hadra": "Hadra",
        "Chopon ota": "Chopon ota",
        "Compas": "Compas",
        "Depomall": "Depomall",
        "Drujba": "Drujba",
        "Farg'ona-1": "Farg'ona-1",
        "Farg'ona-2": "Farg'ona-2",
        "Farxadskiy": "Farxadskiy",
        "Goldenlife": "Goldenlife",
        "Gulzor": "Gulzor",
        "phone":" 📱 Telefon raqami",
        "city": " 🏙 Shahri",
        "info": "Muloqot tili {} \n"
                "Telefon {} \n"
                "Shahar {} ",
        "x_back": "back",
        "closest_branch_loc": "Eng yaqin filialni topish uchun lokatsiyangizni yuboring",

        "eng_yaqin_filial": "yaqin"






    },
    eng_lang:{
        "back_main":"call_back_main",
        "Narxi":"Price",
        "Kartoshka fri":"Fried potatoes",
        "Kartoshka fri katta":"Fried potatoes big",
        "Kartoshka fri kichkina":"Fried potatoes small",
        "Jaydari kartoshka":"Jaydari potato",
        "Non":"Bred",
        "Xalapenyo":"Jalapeño",
        "kartoshka fri":"kartoshka fri",
        "kartoshka fri katta":"kartoshka fri katta",
        "kartoshka fri kichkina":"kartoshka fri kichkina",
        "jaydari kartoshka":"jaydari kartoshka",
        "non":"non",
        "xalapenyo":"xalapenyo",
        "Haggi_tasnifi":"Description: Baguette bread, mayonnaise, beef, lettuce, cucumber, tomato, cheese, red sauce,"
                        """ "Brunswick" sweet onion rings\n Select or enter an amount """,
        "Klab_tasnifi":"Description: Toaster bread, special sauce, cucumber, tomato,"
        " chicken fillet, lettuce, cheese, french fries Choose or enter the amount",
        "Minus":"➖",
        "minus":"minus",
        "Plus":"➕",
        "plus":"plus",
        "Son":"1",
        "son":"son",
        "Savatga qo'shish": "🛒 Add to bag",
        "savatga qo'shish": "savatga qo'shish",
        "Hot-dog":"Hot-dog",
        "Pishloqli Hot-dog":"Cheese Hot-dog",
        "Shohona Hot-dog":"Royal Hot-dog",
        "hot-dog":"hot-dog",
        "pishloqli Hot-dog":"pishloqli Hot-dog",
        "shohona Hot-dog":"shohona Hot-dog",
        "Gamburger":"Hamburger",
        "Chizburger":"Cheeseburger",
        "Big burger":"Big burger",
        "Big Chizburger":"Big Cheeseburger",
        "Big doner":"Big doner",
        "Shaurma":"Shaurma",
        "gamburger":"gamburger",
        "chizburger":"chizburger",
        "big burger":"big burger",
        "big Chizburger":"big Chizburger",
        "big doner":"big doner",
        "shaurma":"shaurma",
        "Assorti pitsa":"Assorti pizza",
        "Pepperoni pitsa":"Pepperoni pizza",
        "Go'shtli pitsa":"Meat pizza",
        "Qazi pitsa":"Qazi pitsa",
        "Tovuqli pitsa":"Chicken pitsa",
        "assorti pitsa":"assorti pitsa",
        "pepperoni pitsa":"pepperoni pitsa",
        "go'shtli pitsa":"go'shtli pitsa",
        "qazi pitsa":"qazi pitsa",
        "tovuqli pitsa":"tovuqli pitsa",
        "Oqtepa Seti":"Oqtepa Set",
        "Juftlik Seti":"Juftlik Set",
        "Baraka Seti":"Baraka Set",
        "oqtepa Seti":"oqtepa Seti",
        "juftlik Seti":"juftlik Seti",
        "baraka Seti":"baraka Seti",
        "Orginal lavash":"Orginal lavash",
        "Orginal kichik lavash":"Orginal small lavash",
        "Pishloqli lavash":"Cheese lavash",
        "Pishloqli kichik lavash":"Cheese small lavash",
        "Tandir lavash":"Tandir lavash",
        "Pishloqli tandir lavash":"Cheese tandir lavash",
        "pishloqli tandir lavash":"pishloqli tandir lavash",
        "orginal lavash":"orginal lavash",
        "orginal kichik lavash":"orginal kichik lavash",
        "pishloqli lavash":"pishloqli lavash",
        "pishloqli kichik lavash":"pishloqli kichik lavash",
        "tandir lavash":"tandir lavash",
        "Ketchup":"Ketchup",
        "Chili sous":"Chili souse",
        "Pishloqli sous":"Cheese souse",
        "Oq sous":"White souse",
        "oq sous":"oq sous",
        "pishloqli sous":"pishloqli sous",
        "chili sous":"chili sous",
        "ketchup":"ketchup",
        "Qaynoq ichimliklar":"Hot drinks",
        "Yahna ichimliklar":"Cold drinks",
        "yahna ichimliklar":"yahna ichimliklar",
        "qaynoq ichimliklar":"qaynoq ichimliklar",
        "Mujskoy kapriz":"Mujskoy kapriz",
        "Sezar":"Sezar",
        "sezar":"sezar",
        "mujskoy kapriz":"mujskoy kapriz",
        "Jo'ja box":"Chicken box",
        "Stips 5 dona":"Stips 5 piece",
        "Stips 3 dona":"Stips 3 piece",
        "Bayts":"Bayts",
        "jo'ja box":"jo'ja box",
        "stips 5 dona":"stips 5 dona",
        "stips 3 dona":"stips 3 dona",
        "bayts":"bayts",
        "Qarsildoq Jo'jalar":"🍗 Crunchy chicks",
        "Salatlar":"🥗 Salads",
        "Ichimliklar":"🥤Drinkings",
        "Souslar":"🍅 Souses",
        "Lavashlar":"🌯 Lavashs",
        "Setlar":"🌯🥤🍟 Sets",
        "Pistalar":"🍕 Pitsa",
        "Burger va donerlar":"🍔 Burgers and doners",
        "Hot doglar":"🌭 Hot dogs",
        "Haggi":"🥙 Haggi",
        "Klab sendvich":"🥪 Klab sendvich",
        "Sneklar":"🍟 Snacks",
        "Asosiy menu":"⬅️ Main menu",
        "username":"Mr/Ms X ",
        "qarsildoq jo'jalar":"callqarsildoq jo'jalar",
        "salatlar":"callsalatlar",
        "ichimliklar":"callichimliklar",
        "souslar":"callsouslar",
        "lavashlar":"calllavashlar",
        "setlar":"callsetlar",
        "pistalar":"callpistalar",
        "burger va donerlar":"callburger va donerlar",
        "hot doglar":"callhot doglar",
        "haggi":"callhaggi",
        "klab sendvich":"callklab sendvich",
        "sneklar":"callsneklar",
        "asosiy menu":"callasosiy menu",
        "name": "Enter your name",
        "phone_number":"telefon",
        "phone_change": "📞 My number",
        "phone_ask":"*Send your mobile number*",
        "aniq_manzil":"Enter your additional address information\n"
                      "*For example:* Train no., floor no., door code no., sq. no..",
        "Ask_contact": "Click the send phone number button! ",
        "send_contact": "📱 Send phone number",
        "yes":" ✅ Yes",
        "no":" ❎ No",
        "ask_loc_true":"The address you want to order from:"
                       "*{}*\n"
                       "Confirm this address?",
        "ask_location": "Turn on *geo-location* for *delivery*!",
        "location": "📍Send geo location ",
        "order": "Order 🛒",
        "about_us": "ℹ️ About us",
        "my_orders": "🛍 My orders",
        "branches": "🏘 Branches",
        "rewiev": "✍️ Rewiev",
        "settings": "⚙️ Settings",
        "welcome_text":" Hello {} To start ordering 🛒" 
                       "Click the order button " 
                       "\n\n" 
                       "You can also see promotions and get to know our affiliates",
        "back": "⬅️ Back",
        "🚴‍♂️ Eltib berish": "🚴‍♂️  Delivery",
        "🚶 Borib olish": "🚶 Take away",
        "borib olish":"Send *geo-location* for *pickup*, \n"
        "We will find a branch near you",
        "buyurtma turi": "Select the order type !",
        "ask": "Will we place the order together? 🤗",
        "about_us_info": "We have been operating in the market of Uzbekistan for 12 years and today we have more than 50 branches throughout the country. Customers who are satisfied with delicious and nutritious food, affordable prices, and fast delivery service choose us again and again \n"
                          "We recommend that you definitely try our hot and delicious lavash, shawarma doners, hamburgers and pizzas, and don't forget to add our chicken novelties to your order!"
                          f"\n"
                          f"\n"
                          f"\n"
                          f"\n"
                          f"Delivery service:  +998781500030",
        "my_last_order": """
        Order number => \n
     Status => \n
     Address => \n
     Product Name => \n
     Amount to be paid => \n
     Paid => """,
    "goback": " ❌ Close",
         "branch_names": "Branches",
        "about_branches": "Our branches: 63 (1-10)",
        "about_branches_page_two":"Our branches: 63 (11-20)",
         "main_menu": " ⬅️ Main menu",
         "main_menu1": " ⬅️ Main menu",
        "back_button1": " ⬅️ Back",
        "closest_branch": "Closest branch 🏠",
        "closest_branch1": "Closest branch 🏠",
        "next_button": "Next page ⏭",
        "next_button1": "Next page ⏭",
        "next1": "Next",
        "cb_next_button1": "Keyingisi",
        "Algoritm": "Algoritm",
        "Andijon-1": "Andijon-1",
        "Bektemir": "Bektemir",
        "Beruniy": "Beruniy",
        "Bodomzor": "Bodomzor",
        "Chigatoy": "Chigatoy",
        "Chilonzor 19": "Chilonzor 19",
        "Chilonzor metro": "Chilonzor metro",
        "Chinoz": "Chinoz",
        "Chirchiq": "Chirchiq",
        "🏠 Algoritm": "Algoritm",
        "🏠 Andijon-1": "Andijon-1",
        "🏠 Bektemir": "Bektemir",
        "🏠 Beruniy": "Beruniy",
        "🏠 Bodomzor": "Bodomzor",
        "🏠 Chigatoy": "Chigatoy",
        "🏠 Chilonzor 19": "Chilonzor 19",
        "🏠 Chilonzor metro": "Chilonzor metro",
        "🏠 Chinoz": "Chinoz",
        "🏠 Chirchiq": "Chirchiq",
        "Hadra": "Hadra",
        "Chopon ota": "Chopon ota",
        "Compas": "Compas",
        "Depomall": "Depomall",
        "Drujba": "Drujba",
        "Farg'ona-1": "Farg'ona-1",
        "Farg'ona-2": "Farg'ona-2",
        "Farxadskiy": "Farxadskiy",
        "Goldenlife": "Goldenlife",
        "Gulzor": "Gulzor",
        "phone":" 📱 Phone number",
        "city": " 🏙 City",
        "info": "Language {} \n"
                "Phone number {} \n"
                "City {} ",
        "x_back": "back",
        "closest_branch_loc": "To fine closest branch send your location",

        "eng_yaqin_filial": "yaqin"
    }
}